//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Real_estate
{
    using System;
    using System.Collections.Generic;
    
    public partial class Houses
    {
        public long Id { get; set; }
        public Nullable<long> IdObject { get; set; }
        public Nullable<int> TotalFloor { get; set; }
        public Nullable<int> Rooms { get; set; }
    
        public virtual Object_of_realEstate Object_of_realEstate { get; set; }
    }
}
